"use client"

import { Button } from "@/components/ui/button"
import { PopoverContent } from "@/components/ui/popover"
import { APP_NAME } from "@/lib/config"
import { ArrowUpRight } from "@phosphor-icons/react"
import Image from "next/image"

interface PopoverContentWelcomeProps {
  firstName?: string
  onGetStarted: () => void
}

export function PopoverContentWelcome({
  firstName,
  onGetStarted,
}: PopoverContentWelcomeProps) {
  return (
    <PopoverContent
      className="w-[300px] overflow-hidden rounded-xl p-0"
      side="top"
      align="start"
    >
      <Image
        src="/banner_forest.jpg"
        alt={`calm paint generated by ${APP_NAME}`}
        width={300}
        height={128}
        className="h-32 w-full object-cover"
      />
      <div className="p-3">
        <p className="text-primary mb-1 text-base font-medium">
          Welcome{firstName ? `, ${firstName}` : ""}! 🎉
        </p>
        <p className="text-muted-foreground mb-5 text-base">
          You're all set up. Ask me anything about prospect research, donor
          screening, or fundraising strategy!
        </p>
        <Button
          onClick={onGetStarted}
          variant="outline"
          className="group flex h-12 w-full items-center justify-between rounded-full border-gray-900 bg-gray-900 py-2 pr-2 pl-6 text-white shadow-sm transition-all hover:scale-[1.02] hover:bg-white hover:text-gray-900 active:scale-[0.98]"
        >
          Get Started{" "}
          <div className="ml-2 rounded-full bg-white/20 p-2 backdrop-blur-sm transition-colors group-hover:bg-gray-900">
            <ArrowUpRight className="h-4 w-4 text-white" weight="bold" />
          </div>
        </Button>
      </div>
    </PopoverContent>
  )
}
