"use client"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { APP_NAME } from "@/lib/config"
import Image from "next/image"
import Link from "next/link"

type DialogLimitReachedProps = {
  open: boolean
  setOpen: (open: boolean) => void
}

export function DialogLimitReached({
  open,
  setOpen,
}: DialogLimitReachedProps) {
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="w-[90%] max-w-[300px] overflow-hidden rounded-xl p-0 sm:max-w-[300px]">
        <DialogHeader className="sr-only">
          <DialogTitle>Monthly message limit reached</DialogTitle>
          <DialogDescription>
            Wait until next month or upgrade to Max/Ultra to continue your workflow.
          </DialogDescription>
        </DialogHeader>
        <div>
          <Image
            src="/banner_forest.jpg"
            alt={`calm paint generated by ${APP_NAME}`}
            width={300}
            height={128}
            className="h-32 w-full object-cover"
          />
          <div className="p-4">
            <div className="text-primary mb-1 text-base font-medium">
              Monthly message limit reached
            </div>
            <p className="text-muted-foreground mb-5 text-base">
              Wait until next month or upgrade to Pro/Scale to continue your
              workflow. Visit Settings → Subscription to upgrade.
            </p>
            <Button
              variant="secondary"
              className="w-full text-base"
              size="lg"
              onClick={() => setOpen(false)}
            >
              <span>Close</span>
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
