"use client"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { APP_NAME } from "@/lib/config"
import Image from "next/image"

type DialogSubscriptionRequiredProps = {
  open: boolean
  setOpen: (open: boolean) => void
}

export function DialogSubscriptionRequired({
  open,
  setOpen,
}: DialogSubscriptionRequiredProps) {
  const handleViewPlans = () => {
    setOpen(false)
    // Dispatch event to open settings with subscription tab
    window.dispatchEvent(
      new CustomEvent("open-settings", { detail: { tab: "subscription" } })
    )
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="w-[90%] max-w-[300px] overflow-hidden rounded-xl p-0 sm:max-w-[300px]">
        <DialogHeader className="sr-only">
          <DialogTitle>Upgrade to use Rōmy</DialogTitle>
          <DialogDescription>
            Subscribe to start chatting with AI models and unlock all features.
          </DialogDescription>
        </DialogHeader>
        <div>
          <Image
            src="/banner_forest.jpg"
            alt={`calm paint generated by ${APP_NAME}`}
            width={300}
            height={128}
            className="h-32 w-full object-cover"
          />
          <div className="p-4">
            <div className="text-primary mb-1 text-base font-medium">
              Upgrade to use Rōmy
            </div>
            <p className="text-muted-foreground mb-4 text-base">
              Subscribe to start chatting with AI models and unlock all
              features.
            </p>
            <Button
              variant="default"
              className="mb-2 w-full text-base"
              size="lg"
              onClick={handleViewPlans}
            >
              <span>View Plans</span>
            </Button>
            <Button
              variant="secondary"
              className="w-full text-base"
              size="lg"
              onClick={() => setOpen(false)}
            >
              <span>Close</span>
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
